version: '3.3'

volumes:
  pg_data:
  static_todo_tracker:
  media_todo_tracker:


services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  todo_tracker:
    image: agas0077/todo_tracker:latest
    env_file: .env
    depends_on:
      - db
    restart: on-failure:2
    volumes:
      - static_todo_tracker:/app/staticfiles/
      - media_todo_tracker:/app/media/
    command: >
      bash -c "python manage.py migrate 
      && python manage.py collectstatic --no-input
      && gunicorn --bind 0.0.0.0:8000 todo_tracker.wsgi"

  nginx:
    depends_on:
        - todo_tracker
    image: nginx:1.19.3
    ports:
      - "8004:80"
    volumes:
      - ./nginx/todo_tracker.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_todo_tracker:/static
      - media_todo_tracker:/media