# Generated by Django 4.1.7 on 2023-03-15 10:55

# Third Party Library
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('task',
                 models.TextField(
                     verbose_name='Задание')),
                ('create_date',
                 models.DateTimeField(
                     auto_now_add=True,
                     verbose_name='Дата создания')),
                ('deadline_date',
                 models.DateTimeField(
                     verbose_name='Дата дедлайна')),
                ('image',
                 models.ImageField(
                     blank=True,
                     null=True,
                     upload_to='todo/',
                     verbose_name='Картинка')),
                ('created_by',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='tasks',
                     to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
