# Generated by Django 4.1.7 on 2023-03-17 13:21

# Third Party Library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название'),
        ),
    ]
